# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ReadItAloud' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReadItAloud
  pod 'Firebase/Core'



  target 'ReadItAloudTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReadItAloud-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReadItAloud-tvOS

  target 'ReadItAloud-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
